ALLOWED_EXTENSIONS = {'xml'}
TEMPORARY_DIRECTORY = '/Users/akmi/eko-temp'
DATAVERSE_BASE_URL='http://localhost:8085'
DDI_CONVERTER_TOOL_LOG_FILE='/Users/akmi/eko-temp/dcl12.log'
DDI_CONVERTER_TOOL_DEBUG=True