# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Body(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, ddi_file: str=None):  # noqa: E501
        """Body - a model defined in Swagger

        :param ddi_file: The ddi_file of this Body.  # noqa: E501
        :type ddi_file: str
        """
        self.swagger_types = {
            'ddi_file': str
        }

        self.attribute_map = {
            'ddi_file': 'ddi_file'
        }
        self._ddi_file = ddi_file

    @classmethod
    def from_dict(cls, dikt) -> 'Body':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The body of this Body.  # noqa: E501
        :rtype: Body
        """
        return util.deserialize_model(dikt, cls)

    @property
    def ddi_file(self) -> str:
        """Gets the ddi_file of this Body.


        :return: The ddi_file of this Body.
        :rtype: str
        """
        return self._ddi_file

    @ddi_file.setter
    def ddi_file(self, ddi_file: str):
        """Sets the ddi_file of this Body.


        :param ddi_file: The ddi_file of this Body.
        :type ddi_file: str
        """

        self._ddi_file = ddi_file
